### ISSUE TITLE
sd_xxx.lua file

### ISSUE THREAD

**Issue by FATJ775** [Radio-Guy/VLC-Radio-Stations#2]
sd_xxx.lua file
Put the pl_xxx.lua files into the according Playlist subfolder of the VLC lua directory—by default:
There is no sd_xxx.lua file in the zip file?

**Comment by ceever** [comment]
There is no "sd_radio_stations.lua"? xxx is a wildcard.

**Comment by Radio-Guy** [comment]
He is right, I will adjust the wording a little ... 👍👍

**Comment by FATJ775** [comment]
THANX!
shit's confusing enough as it is .
